### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by attacker-312231123** [dabroz/csgjs-cpp#1]
I just want to say, thanks for this library, even if it's just a port from other language. You really saved me many hours of work (even though I already been struggling with CSG for past month). Because I found a bug in it - float variables makes too large meshes to crash on boolean operations - soon I will make some pull request to your library, even fork it with some examples. So for now - thanks from other Warsaw dweller! :) (I owe you a big beer)

Cheshire Cat

**Comment by dabroz** [comment]
Sorry for a late response, but great to hear that! :)

We now have much better tools and frameworks for C++ 3D stuff than we had 3.5 years ago, so it definitely would be great to have some easily runnable demos. Bugfixes are welcome as well. :)
