### ISSUE TITLE
Forgot to add else branch?

### ISSUE THREAD

**Issue by xahon** [dabroz/csgjs-cpp#4]
https://github.com/dabroz/csgjs-cpp/blob/76d7ff2d82bbb31459b0bc4c09633320fc49d2fb/csgjs.cpp#L377

**Comment by dabroz** [comment]
Can you compare with JS version and submit a PR?

**Comment by xahon** [comment]
It look very weird for me. I think js's else is useless https://github.com/evanw/csg.js/blob/a8512afbac3cf503195870f7ef11c0a32f36c6d4/csg.js#L555

**Comment by xahon** [comment]
I'm clearing github subscriptions now and find lots of weird issues of mine. This is one of them :)
